name: Install OneClickInstall DocSpace

on:
  workflow_dispatch:
    inputs:
      os:
        description: Ignored if deb_build or rpm_build is true
        required: false
        default: debian11,debian12,ubuntu2204,ubuntu2404,rhel9,centos9s,fedora41,fedora42

      deb_build:
        type: boolean
        description: Run tests on DEB-based distros
        default: true

      rpm_build:
        type: boolean
        description: Run tests on RPM-based distros
        default: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}

    steps:
      - name: Build test matrix
        id: build
        env:
          OS_MAP: |
            {
              "rhel9":      ["RHEL 9", "generic"],
              "centos9s":   ["CentOS 9 Stream", "onlyoffice"],
              "debian11":   ["Debian 11", "onlyoffice"],
              "debian12":   ["Debian 12", "onlyoffice"],
              "ubuntu2204": ["Ubuntu 22.04", "onlyoffice"],
              "ubuntu2404": ["Ubuntu 24.04", "onlyoffice"],
              "fedora41":   ["Fedora 41", "onlyoffice"],
              "fedora42":   ["Fedora 42", "onlyoffice"]
            }
        shell: bash
        run: |
          DEB="${{ github.event.inputs.deb_build }}"
          RPM="${{ github.event.inputs.rpm_build }}"
          OS_INPUT="${{ github.event.inputs.os }}"

          RAW_LIST=()

          # Always consider manual OS input if present
          if [[ -n "$OS_INPUT" ]]; then
            echo "Including manually selected OS: $OS_INPUT"
            for os in ${OS_INPUT//,/ }; do RAW_LIST+=("$os"); done
          fi

          # Add all DEB-based OS if deb_build is true
          if [[ "$DEB" == "true" ]]; then
            echo "Including all DEB-based OS"
            mapfile -t deb_os < <(jq -r 'to_entries[] | select(.value[0] | test("Debian|Ubuntu")) | .key' <<< "$OS_MAP")
            RAW_LIST+=("${deb_os[@]}")
          fi

          # Add all RPM-based OS if rpm_build is true
          if [[ "$RPM" == "true" ]]; then
            echo "Including all RPM-based OS"
            mapfile -t rpm_os < <(jq -r 'to_entries[] | select(.value[0] | test("CentOS|Fedora|RHEL")) | .key' <<< "$OS_MAP")
            RAW_LIST+=("${rpm_os[@]}")
          fi

          # Deduplicate RAW_LIST
          RAW_LIST=($(printf '%s\n' "${RAW_LIST[@]}" | sort -u))

          jq_input=$(jq -n \
            --argjson map "$(jq <<< "$OS_MAP")" \
            --argjson list "$RAW_JSON" '
            {
              include: $list | map({
                name: $map[.][0],
                os: .,
                distr: $map[.][1]
              })
            }')

          echo "Final matrix:"
          jq <<< "$jq_input"

          echo "matrix=$(jq -c <<< "$jq_input")" >> "$GITHUB_OUTPUT"


  vagrant-up:
    name: "Test DocSpace with ${{ matrix.name}}"
    runs-on: ubuntu-22.04
    needs: prepare
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare.outputs.matrix)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Checking scripts for errors"
        run: |
          set -eux
          sudo apt-get install -y shellcheck
          find install/OneClickInstall tests -type f -name "*.sh" ! -path "install/OneClickInstall/install-Docker.sh" \
            | xargs shellcheck --exclude="$(awk '!/^#|^$/ {print $1}' tests/lint/sc_ignore | paste -sd ",")" --severity=warning | tee sc_output
          awk '/\(warning\):/ {w++} /\(error\):/ {e++} END {if (w+e) printf "::warning ::ShellCheck detected %d warnings and %d errors\n", w+0, e+0}' sc_output

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get update and install vagrant
        run: |
          set -eux
          wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo gpg --dearmor -o /usr/share/keyrings/virtualbox.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian $(. /etc/os-release && echo $UBUNTU_CODENAME) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update -y
          sudo apt install vagrant virtualbox-7.0 -y

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc
          sudo docker image prune --all --force

      - name: "Test production scripts with ${{matrix.name}}"
        if: ${{ github.event_name == 'schedule' }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          timeout_minutes: 80
          retry_on: error
          command: |
            set -eux
            cd tests/vagrant
            TEST_CASE='--production-install' \
            DISTR='${{ matrix.distr }}' \
            OS='${{ matrix.os }}' \
            DOWNLOAD_SCRIPT='-ds true' \
            RAM='8192' \
            CPU='3' \
            ARGUMENTS="-arg '--skiphardwarecheck true'" \
            vagrant up --provider=virtualbox
          on_retry_command: |
            echo "RUN CLEAN UP: Destroy vagrant and one more try"
            cd tests/vagrant
            sleep 10
            vagrant destroy --force

      - name: "Test Local scripts with ${{matrix.name}}"
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          timeout_minutes: 80
          retry_on: error
          command: |
            set -eux
            cd tests/vagrant
            TEST_CASE='--local-install' \
            DISTR='${{ matrix.distr }}' \
            OS='${{matrix.os}}' \
            RAM='8192' \
            CPU='3' \
            DOWNLOAD_SCRIPT='-ds false' \
            TEST_REPO='-tr true' \
            ARGUMENTS="-arg '--skiphardwarecheck true --localscripts true'" \
            vagrant up --provider=virtualbox
          on_retry_command: |
            echo "RUN CLEAN UP: Destroy vagrant and one more try"
            cd tests/vagrant
            sleep 10
            vagrant destroy --force
